/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DocumentVerification } from "./DocumentVerification";
export type { EligibilityVerification } from "./EligibilityVerification";
export type { SchemeRegistry } from "./SchemeRegistry";
export type { WelfareAudit } from "./WelfareAudit";
export type { WelfareDistribution } from "./WelfareDistribution";
export type { WelfareRegistry } from "./WelfareRegistry";
export type { WelfareToken } from "./WelfareToken";
export type { WelfareVerification } from "./WelfareVerification";
