/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WelfareRegistry {
  export type BeneficiaryHistoryStruct = {
    program: string;
    amount: BigNumberish;
    date: BigNumberish;
  };

  export type BeneficiaryHistoryStructOutput = [
    program: string,
    amount: bigint,
    date: bigint
  ] & { program: string; amount: bigint; date: bigint };
}

export interface WelfareRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addBeneficiaryHistory"
      | "beneficiaryHistory"
      | "beneficiaryHistoryCount"
      | "beneficiaryInfo"
      | "getBeneficiaryHistory"
      | "getBeneficiaryHistoryCount"
      | "isBeneficiary"
      | "isMinistry"
      | "owner"
      | "registerBeneficiary"
      | "registerMinistry"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateBeneficiaryInfo"
      | "updateBeneficiaryStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BeneficiaryHistoryAdded"
      | "BeneficiaryInfoUpdated"
      | "BeneficiaryRegistered"
      | "BeneficiaryStatusUpdated"
      | "MinistryRegistered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addBeneficiaryHistory",
    values: [AddressLike, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiaryHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiaryHistoryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiaryInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaryHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaryHistoryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMinistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMinistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBeneficiaryInfo",
    values: [
      AddressLike,
      string,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBeneficiaryStatus",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "addBeneficiaryHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beneficiaryHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beneficiaryHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beneficiaryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaryHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaryHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMinistry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMinistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBeneficiaryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBeneficiaryStatus",
    data: BytesLike
  ): Result;
}

export namespace BeneficiaryHistoryAddedEvent {
  export type InputTuple = [beneficiary: AddressLike];
  export type OutputTuple = [beneficiary: string];
  export interface OutputObject {
    beneficiary: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeneficiaryInfoUpdatedEvent {
  export type InputTuple = [beneficiary: AddressLike];
  export type OutputTuple = [beneficiary: string];
  export interface OutputObject {
    beneficiary: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeneficiaryRegisteredEvent {
  export type InputTuple = [beneficiary: AddressLike];
  export type OutputTuple = [beneficiary: string];
  export interface OutputObject {
    beneficiary: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeneficiaryStatusUpdatedEvent {
  export type InputTuple = [beneficiary: AddressLike, status: boolean];
  export type OutputTuple = [beneficiary: string, status: boolean];
  export interface OutputObject {
    beneficiary: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinistryRegisteredEvent {
  export type InputTuple = [ministry: AddressLike];
  export type OutputTuple = [ministry: string];
  export interface OutputObject {
    ministry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WelfareRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): WelfareRegistry;
  waitForDeployment(): Promise<this>;

  interface: WelfareRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addBeneficiaryHistory: TypedContractMethod<
    [
      beneficiary: AddressLike,
      program: string,
      amount: BigNumberish,
      date: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  beneficiaryHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint] & {
        program: string;
        amount: bigint;
        date: bigint;
      }
    ],
    "view"
  >;

  beneficiaryHistoryCount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  beneficiaryInfo: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, bigint, bigint, boolean] & {
        name: string;
        age: bigint;
        location: string;
        income: bigint;
        familySize: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getBeneficiaryHistory: TypedContractMethod<
    [beneficiary: AddressLike, index: BigNumberish],
    [WelfareRegistry.BeneficiaryHistoryStructOutput],
    "view"
  >;

  getBeneficiaryHistoryCount: TypedContractMethod<
    [beneficiary: AddressLike],
    [bigint],
    "view"
  >;

  isBeneficiary: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isMinistry: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerBeneficiary: TypedContractMethod<
    [beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  registerMinistry: TypedContractMethod<
    [ministry: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateBeneficiaryInfo: TypedContractMethod<
    [
      beneficiary: AddressLike,
      name: string,
      age: BigNumberish,
      location: string,
      income: BigNumberish,
      familySize: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateBeneficiaryStatus: TypedContractMethod<
    [beneficiary: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addBeneficiaryHistory"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      program: string,
      amount: BigNumberish,
      date: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beneficiaryHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint] & {
        program: string;
        amount: bigint;
        date: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "beneficiaryHistoryCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "beneficiaryInfo"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, bigint, bigint, boolean] & {
        name: string;
        age: bigint;
        location: string;
        income: bigint;
        familySize: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBeneficiaryHistory"
  ): TypedContractMethod<
    [beneficiary: AddressLike, index: BigNumberish],
    [WelfareRegistry.BeneficiaryHistoryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBeneficiaryHistoryCount"
  ): TypedContractMethod<[beneficiary: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isBeneficiary"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMinistry"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerBeneficiary"
  ): TypedContractMethod<[beneficiary: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerMinistry"
  ): TypedContractMethod<[ministry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBeneficiaryInfo"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      name: string,
      age: BigNumberish,
      location: string,
      income: BigNumberish,
      familySize: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateBeneficiaryStatus"
  ): TypedContractMethod<
    [beneficiary: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BeneficiaryHistoryAdded"
  ): TypedContractEvent<
    BeneficiaryHistoryAddedEvent.InputTuple,
    BeneficiaryHistoryAddedEvent.OutputTuple,
    BeneficiaryHistoryAddedEvent.OutputObject
  >;
  getEvent(
    key: "BeneficiaryInfoUpdated"
  ): TypedContractEvent<
    BeneficiaryInfoUpdatedEvent.InputTuple,
    BeneficiaryInfoUpdatedEvent.OutputTuple,
    BeneficiaryInfoUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BeneficiaryRegistered"
  ): TypedContractEvent<
    BeneficiaryRegisteredEvent.InputTuple,
    BeneficiaryRegisteredEvent.OutputTuple,
    BeneficiaryRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "BeneficiaryStatusUpdated"
  ): TypedContractEvent<
    BeneficiaryStatusUpdatedEvent.InputTuple,
    BeneficiaryStatusUpdatedEvent.OutputTuple,
    BeneficiaryStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinistryRegistered"
  ): TypedContractEvent<
    MinistryRegisteredEvent.InputTuple,
    MinistryRegisteredEvent.OutputTuple,
    MinistryRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BeneficiaryHistoryAdded(address)": TypedContractEvent<
      BeneficiaryHistoryAddedEvent.InputTuple,
      BeneficiaryHistoryAddedEvent.OutputTuple,
      BeneficiaryHistoryAddedEvent.OutputObject
    >;
    BeneficiaryHistoryAdded: TypedContractEvent<
      BeneficiaryHistoryAddedEvent.InputTuple,
      BeneficiaryHistoryAddedEvent.OutputTuple,
      BeneficiaryHistoryAddedEvent.OutputObject
    >;

    "BeneficiaryInfoUpdated(address)": TypedContractEvent<
      BeneficiaryInfoUpdatedEvent.InputTuple,
      BeneficiaryInfoUpdatedEvent.OutputTuple,
      BeneficiaryInfoUpdatedEvent.OutputObject
    >;
    BeneficiaryInfoUpdated: TypedContractEvent<
      BeneficiaryInfoUpdatedEvent.InputTuple,
      BeneficiaryInfoUpdatedEvent.OutputTuple,
      BeneficiaryInfoUpdatedEvent.OutputObject
    >;

    "BeneficiaryRegistered(address)": TypedContractEvent<
      BeneficiaryRegisteredEvent.InputTuple,
      BeneficiaryRegisteredEvent.OutputTuple,
      BeneficiaryRegisteredEvent.OutputObject
    >;
    BeneficiaryRegistered: TypedContractEvent<
      BeneficiaryRegisteredEvent.InputTuple,
      BeneficiaryRegisteredEvent.OutputTuple,
      BeneficiaryRegisteredEvent.OutputObject
    >;

    "BeneficiaryStatusUpdated(address,bool)": TypedContractEvent<
      BeneficiaryStatusUpdatedEvent.InputTuple,
      BeneficiaryStatusUpdatedEvent.OutputTuple,
      BeneficiaryStatusUpdatedEvent.OutputObject
    >;
    BeneficiaryStatusUpdated: TypedContractEvent<
      BeneficiaryStatusUpdatedEvent.InputTuple,
      BeneficiaryStatusUpdatedEvent.OutputTuple,
      BeneficiaryStatusUpdatedEvent.OutputObject
    >;

    "MinistryRegistered(address)": TypedContractEvent<
      MinistryRegisteredEvent.InputTuple,
      MinistryRegisteredEvent.OutputTuple,
      MinistryRegisteredEvent.OutputObject
    >;
    MinistryRegistered: TypedContractEvent<
      MinistryRegisteredEvent.InputTuple,
      MinistryRegisteredEvent.OutputTuple,
      MinistryRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
