/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WelfareVerificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getVerificationHash"
      | "isBeneficiary"
      | "isMinistry"
      | "isVerified"
      | "owner"
      | "registerBeneficiary"
      | "registerMinistry"
      | "renounceOwnership"
      | "transferOwnership"
      | "verificationHash"
      | "verifyDocuments"
      | "welfareToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BeneficiaryRegistered"
      | "DocumentsVerified"
      | "MinistryRegistered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getVerificationHash",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMinistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMinistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationHash",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocuments",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "welfareToken",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getVerificationHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMinistry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMinistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocuments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "welfareToken",
    data: BytesLike
  ): Result;
}

export namespace BeneficiaryRegisteredEvent {
  export type InputTuple = [beneficiary: AddressLike];
  export type OutputTuple = [beneficiary: string];
  export interface OutputObject {
    beneficiary: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentsVerifiedEvent {
  export type InputTuple = [beneficiary: AddressLike, documentHash: BytesLike];
  export type OutputTuple = [beneficiary: string, documentHash: string];
  export interface OutputObject {
    beneficiary: string;
    documentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinistryRegisteredEvent {
  export type InputTuple = [ministry: AddressLike];
  export type OutputTuple = [ministry: string];
  export interface OutputObject {
    ministry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WelfareVerification extends BaseContract {
  connect(runner?: ContractRunner | null): WelfareVerification;
  waitForDeployment(): Promise<this>;

  interface: WelfareVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getVerificationHash: TypedContractMethod<
    [beneficiary: AddressLike],
    [string],
    "view"
  >;

  isBeneficiary: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isMinistry: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isVerified: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerBeneficiary: TypedContractMethod<
    [beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  registerMinistry: TypedContractMethod<
    [ministry: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verificationHash: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  verifyDocuments: TypedContractMethod<
    [beneficiary: AddressLike, documentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  welfareToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getVerificationHash"
  ): TypedContractMethod<[beneficiary: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isBeneficiary"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMinistry"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerBeneficiary"
  ): TypedContractMethod<[beneficiary: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerMinistry"
  ): TypedContractMethod<[ministry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verificationHash"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "verifyDocuments"
  ): TypedContractMethod<
    [beneficiary: AddressLike, documentHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "welfareToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BeneficiaryRegistered"
  ): TypedContractEvent<
    BeneficiaryRegisteredEvent.InputTuple,
    BeneficiaryRegisteredEvent.OutputTuple,
    BeneficiaryRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DocumentsVerified"
  ): TypedContractEvent<
    DocumentsVerifiedEvent.InputTuple,
    DocumentsVerifiedEvent.OutputTuple,
    DocumentsVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "MinistryRegistered"
  ): TypedContractEvent<
    MinistryRegisteredEvent.InputTuple,
    MinistryRegisteredEvent.OutputTuple,
    MinistryRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BeneficiaryRegistered(address)": TypedContractEvent<
      BeneficiaryRegisteredEvent.InputTuple,
      BeneficiaryRegisteredEvent.OutputTuple,
      BeneficiaryRegisteredEvent.OutputObject
    >;
    BeneficiaryRegistered: TypedContractEvent<
      BeneficiaryRegisteredEvent.InputTuple,
      BeneficiaryRegisteredEvent.OutputTuple,
      BeneficiaryRegisteredEvent.OutputObject
    >;

    "DocumentsVerified(address,bytes32)": TypedContractEvent<
      DocumentsVerifiedEvent.InputTuple,
      DocumentsVerifiedEvent.OutputTuple,
      DocumentsVerifiedEvent.OutputObject
    >;
    DocumentsVerified: TypedContractEvent<
      DocumentsVerifiedEvent.InputTuple,
      DocumentsVerifiedEvent.OutputTuple,
      DocumentsVerifiedEvent.OutputObject
    >;

    "MinistryRegistered(address)": TypedContractEvent<
      MinistryRegisteredEvent.InputTuple,
      MinistryRegisteredEvent.OutputTuple,
      MinistryRegisteredEvent.OutputObject
    >;
    MinistryRegistered: TypedContractEvent<
      MinistryRegisteredEvent.InputTuple,
      MinistryRegisteredEvent.OutputTuple,
      MinistryRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
