/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { IERC1155Errors } from "./@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC1155Errors";
export { IERC1155Errors__factory } from "./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC1155Errors__factory";
export type { IERC20Errors } from "./@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC20Errors";
export { IERC20Errors__factory } from "./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC20Errors__factory";
export type { IERC721Errors } from "./@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC721Errors";
export { IERC721Errors__factory } from "./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC721Errors__factory";
export type { ERC20 } from "./@openzeppelin/contracts/token/ERC20/ERC20";
export { ERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/ERC20__factory";
export type { IERC20Metadata } from "./@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata";
export { IERC20Metadata__factory } from "./factories/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata__factory";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { DocumentVerification } from "./contracts/DocumentVerification";
export { DocumentVerification__factory } from "./factories/contracts/DocumentVerification__factory";
export type { EligibilityVerification } from "./contracts/EligibilityVerification";
export { EligibilityVerification__factory } from "./factories/contracts/EligibilityVerification__factory";
export type { SchemeRegistry } from "./contracts/SchemeRegistry";
export { SchemeRegistry__factory } from "./factories/contracts/SchemeRegistry__factory";
export type { WelfareAudit } from "./contracts/WelfareAudit";
export { WelfareAudit__factory } from "./factories/contracts/WelfareAudit__factory";
export type { WelfareDistribution } from "./contracts/WelfareDistribution";
export { WelfareDistribution__factory } from "./factories/contracts/WelfareDistribution__factory";
export type { WelfareRegistry } from "./contracts/WelfareRegistry";
export { WelfareRegistry__factory } from "./factories/contracts/WelfareRegistry__factory";
export type { WelfareToken } from "./contracts/WelfareToken";
export { WelfareToken__factory } from "./factories/contracts/WelfareToken__factory";
export type { WelfareVerification } from "./contracts/WelfareVerification";
export { WelfareVerification__factory } from "./factories/contracts/WelfareVerification__factory";
